apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper
  labels:
    app: gatekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatekeeper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gatekeeper
    spec:
      containers:
        - name: gatekeeper
          image: keycloak/keycloak-gatekeeper:7.0.0
          ports:
            - containerPort: 3000
          args:
            - --discovery-url=https://sibus.ambq.gov.co/auth/realms/DEVICES
            - --client-id=devices
            - --client-secret=985d96f0-2d5e-487f-8a8a-550cd4616751
            - --listen=0.0.0.0:3000
            - --redirection-url=https://sibus.ambq.gov.co
            - --enable-refresh-tokens=true
            - --encryption-key=AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2k
            - --upstream-url=http://updatevoc-svc.default.svc.cluster.local:8000
            - --enable-default-deny=true
            - --resources=uri=/updatevoc/api/v2/*|roles=DEVICE_VOC
            - --resources=uri=/updatevoc/static*|roles=DEVICE_VOC
            - --resources=uri=/updatevoc/data/*|roles=ORGANIZATION_WRITE
            - --resources=uri=/updatevoc/api/v2/files|roles=ORGANIZATION_WRITE|methods=POST
            - --resources=uri=/static*|white-listed=true
            - --resources=uri=/updatevoc/api/v1/*|white-listed=true
            - --headers=myheader1=value1
            - --headers=myheader2=value2
            - --verbose
            - --enable-logging
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper
  labels:
    app: gatekeeper
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: gatekeeper
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/client_max_body_size: 32m
  name: ingress-updatevoc
  namespace: default
spec:
  rules:
  - host: sibus.ambq.gov.co
    http:
      paths:
      - path: /updatevoc
        backend:
          service:
            name: gatekeeper
            port:
              number: 3000
        pathType: ImplementationSpecific
      - path: /oauth
        backend:
          service:
            name: gatekeeper
            port:
              number: 3000
        pathType: ImplementationSpecific
      - path: /static
        backend:
          service:
            name: gatekeeper
            port:
              number: 3000
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - sibus.ambq.gov.co
    secretName: tls-main
